package net.neoforged.meta.extract;

import net.neoforged.meta.config.SoftwareComponentProperties;
import org.jspecify.annotations.Nullable;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * Given a changelog generated by gradleutils, try to extract a nice entry for just a single version.
 */
public final class ChangelogExtractor {
    private ChangelogExtractor() {
    }

    @Nullable
    public static String extract(byte[] changelogBody) {
        String[] lines = new String(changelogBody, StandardCharsets.UTF_8).split("\n");

        // Auto-Switch to parse the old format used in Forge 1.20.1
        Pattern startOfChangelogPattern;
        int start;
        if (lines.length > 3 && lines[0].endsWith(" Changelog") && lines[2].equals("====")) {
            start = 3;
            startOfChangelogPattern = Pattern.compile("^ - \\d+\\.\\S+\\s+");
        } else {
            start = 0;
            startOfChangelogPattern = Pattern.compile("^ - `[^`]+` ");
        }

        for (int i = start; i < lines.length; i++) {
            var line = lines[i];
            Matcher matcher = startOfChangelogPattern.matcher(line);
            if (matcher.find()) {
                line = line.replace("\r", "");
                // Found the version, now scan all
                var versionEntry = new StringBuilder();
                versionEntry.append(line.substring(matcher.group().length()));
                // Append any continuation lines.
                for (int j = i + 1; j < lines.length; j++) {
                    var continuationLine = lines[j];
                    if (continuationLine.startsWith("   ")) {
                        continuationLine = continuationLine.replace("\r", "");
                        versionEntry.append('\n').append(continuationLine.substring(3));
                    } else break;
                }

                return versionEntry.toString();
            }
        }

        return null;
    }

    public static String extractText(SoftwareComponentProperties properties, String originalText) {
        originalText = cleanUpOriginal(originalText);

        return originalText;
    }

    public static String extractMarkdown(SoftwareComponentProperties properties, String originalText) {
        var markdownText = originalText;

        markdownText = cleanUpOriginal(markdownText);

        // Auto replace http-URLs with links to those URLs.
        // But some commit messages already contain Markdown links, since they're copied from GitHub
        markdownText = markdownText.replaceAll(
                "(?<![\"(])(https?://[^\\s<>\"{}|\\\\^`\\[\\]]+)(?![\")])",
                "[$1]($1)"
        );

        // Replace #123 with a link to https://github.com/org/repo/issues/123
        if (properties.getGithubRepository() != null) {
            var repoUrl = "https://github.com/" + Arrays.stream(properties.getGithubRepository().split("/")).map(s -> URLEncoder.encode(s, StandardCharsets.UTF_8)).collect(Collectors.joining("/"));
            markdownText = markdownText.replaceAll("#([1-9]\\d*)", "[#$1](" + Matcher.quoteReplacement(repoUrl) + "/issues/$1)");
        }

        return markdownText;
    }

    private static String cleanUpOriginal(String originalText) {
        // Strip leading Minecraft or Neo version tags from Commit messages as those are redundantin changelogs that
        // are shown directly next to that version
        originalText = originalText.replaceAll("(?i)^\\s*\\[(?:backport|backport\\s+to)?\\s*\\d+\\.\\d+[.x\\d]*]\\s*", "");

        // Strip Co-Author tags, since we don't credit the original author either and we don't want to expose those E-Mails on CF
        originalText = originalText.replaceAll("(?i)\\s*(Co-authored-by|Signed-off-by):[^\n]+", "");

        // Strip separators since those will be converted to rules in markdown which are unwieldy
        originalText = originalText.replaceAll("\\n\\s*---+\\s*($|\\Z)", "");

        // Trim extra whitespace at the end of lines
        originalText = originalText.replaceAll("[^\\S\\r\\n]+\\n", "\n");

        // Trim extra whitespace around the entire text
        originalText = originalText.trim();

        return originalText;
    }
}
