package net.neoforged.meta.extract;

import net.neoforged.meta.db.SoftwareComponentChangelog;
import org.jspecify.annotations.Nullable;

import java.nio.charset.StandardCharsets;

/**
 * Given a changelog generated by gradleutils, try to extract a nice entry for just a single version.
 */
public final class ChangelogExtractor {
    private ChangelogExtractor() {
    }

    @Nullable
    public static String extract(byte[] changelogBody, String version) {
        String[] lines = new String(changelogBody, StandardCharsets.UTF_8).split("\n");
        for (int i = 0; i < lines.length; i++) {
            var line = lines[i];
            String linePrefix = " - `" + version + "` ";
            if (line.startsWith(linePrefix)) {
                line = line.replace("\r", "");
                // Found the version, now scan all
                var versionEntry = new StringBuilder();
                versionEntry.append(line.substring(linePrefix.length()));
                // Append any continuation lines.
                for (int j = i + 1; j < lines.length; j++) {
                    var continuationLine = lines[j];
                    if (continuationLine.startsWith("   ")) {
                        continuationLine = continuationLine.replace("\r", "");
                        versionEntry.append('\n').append(continuationLine.substring(3));
                    } else break;
                }

                return versionEntry.toString();
            }
        }

        return null;
    }
}
